/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.reto_equipo3.Swing;

import com.mycompany.reto_equipo3.Actividad;
import com.mycompany.reto_equipo3.DAOS.DAOActividad;
import com.mycompany.reto_equipo3.DAOS.DAOPuntosinteres;
import com.mycompany.reto_equipo3.DAOS.DAOPuntospeligro;
import com.mycompany.reto_equipo3.DAOS.DAORutas;
import com.mycompany.reto_equipo3.DAOS.DAOUsuario;
import com.mycompany.reto_equipo3.DAOS.DAOValora;
import com.mycompany.reto_equipo3.Enums.Roles;
import com.mycompany.reto_equipo3.PuntosInteres;
import com.mycompany.reto_equipo3.PuntosPeligro;
import com.mycompany.reto_equipo3.Rutas;
import com.mycompany.reto_equipo3.Usuario;
import com.mycompany.reto_equipo3.Validaciones.Teclado;
import com.mycompany.reto_equipo3.Valora;
import java.awt.Dimension;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author salsa
 */
public class SwingPrincipal extends javax.swing.JFrame {

    Usuario usuario = null;
    int idrutaapipp;

    public SwingPrincipal() {
        initComponents();
        setResizable(false);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.out.println("Cierre deshabilitado.");
            }
        });
        // Reajustar Tamaño de rutas validas tabla
        this.TableRutasValidas.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);
        jScrollPane1.setPreferredSize(new Dimension(1600, 600));
    }

    // Tamaño de lo que ocupa cada cuadrado de la tabla valida rutas
    public void tamañocolumnasRutaValidas() {
        this.TableRutasValidas.getColumnModel().getColumn(0).setPreferredWidth(100);
        this.TableRutasValidas.getColumnModel().getColumn(1).setPreferredWidth(200);
        this.TableRutasValidas.getColumnModel().getColumn(2).setPreferredWidth(150);
        this.TableRutasValidas.getColumnModel().getColumn(3).setPreferredWidth(150);
        this.TableRutasValidas.getColumnModel().getColumn(4).setPreferredWidth(200);
        this.TableRutasValidas.getColumnModel().getColumn(5).setPreferredWidth(150);
        this.TableRutasValidas.getColumnModel().getColumn(6).setPreferredWidth(150);
        this.TableRutasValidas.getColumnModel().getColumn(7).setPreferredWidth(200);
        this.TableRutasValidas.getColumnModel().getColumn(8).setPreferredWidth(150);
        this.TableRutasValidas.getColumnModel().getColumn(9).setPreferredWidth(150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEntrada = new javax.swing.JPanel();
        CuadroEntrada = new javax.swing.JLabel();
        Iconoderecha1 = new javax.swing.JLabel();
        BotonEntrada = new javax.swing.JButton();
        FondoEntrada = new javax.swing.JLabel();
        PanelInicio = new javax.swing.JPanel();
        TextoInicio = new javax.swing.JLabel();
        Salida = new javax.swing.JButton();
        Rutas = new javax.swing.JButton();
        Usuario = new javax.swing.JButton();
        Cuadro2 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        Cuadro1 = new javax.swing.JLabel();
        IniciarSesion = new javax.swing.JButton();
        Contraseña = new javax.swing.JPasswordField();
        Logoderecha = new javax.swing.JLabel();
        Seleccion = new javax.swing.JPanel();
        Cuadroinfo = new javax.swing.JLabel();
        Nombrecambia = new javax.swing.JLabel();
        BotonVolver = new javax.swing.JButton();
        CrearUsuarios = new javax.swing.JPanel();
        Texto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        intronombre = new javax.swing.JTextField();
        apellido = new javax.swing.JLabel();
        introapellido = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        introemail = new javax.swing.JTextField();
        contraseña = new javax.swing.JLabel();
        rol = new javax.swing.JLabel();
        eligerol = new javax.swing.JComboBox<>();
        introcontraseña = new javax.swing.JPasswordField();
        VolverUsuarios = new javax.swing.JButton();
        darbotonUsuario = new javax.swing.JButton();
        RutasValidas = new javax.swing.JPanel();
        VolverInicio = new javax.swing.JButton();
        NombreRutas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableRutasValidas = new javax.swing.JTable();
        PuntosdeRuta = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablePuntosInteres = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablePuntosPeligro = new javax.swing.JTable();
        ValoracionesdeRuta = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaValoraciones = new javax.swing.JTable();
        Actividades = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablaActividades = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        DetallesRuta = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TablaDetallesruta = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        PanelEntrada.setBackground(new java.awt.Color(153, 255, 153));
        PanelEntrada.setForeground(new java.awt.Color(255, 255, 255));
        PanelEntrada.setMaximumSize(new java.awt.Dimension(600, 400));
        PanelEntrada.setMinimumSize(new java.awt.Dimension(600, 400));
        PanelEntrada.setPreferredSize(new java.awt.Dimension(600, 400));

        CuadroEntrada.setBackground(new java.awt.Color(0, 0, 0));
        CuadroEntrada.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        CuadroEntrada.setForeground(new java.awt.Color(51, 51, 255));
        CuadroEntrada.setText("Aplicacion de Rutas");
        CuadroEntrada.setAlignmentX(200.0F);
        CuadroEntrada.setAlignmentY(200.0F);

        BotonEntrada.setBackground(new java.awt.Color(51, 255, 51));
        BotonEntrada.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        BotonEntrada.setForeground(new java.awt.Color(0, 102, 0));
        BotonEntrada.setText("Iniciar aplicacion");
        BotonEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEntradaLayout = new javax.swing.GroupLayout(PanelEntrada);
        PanelEntrada.setLayout(PanelEntradaLayout);
        PanelEntradaLayout.setHorizontalGroup(
            PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEntradaLayout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addGroup(PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEntradaLayout.createSequentialGroup()
                        .addComponent(CuadroEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155)
                        .addComponent(Iconoderecha1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEntradaLayout.createSequentialGroup()
                        .addComponent(BotonEntrada)
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEntradaLayout.createSequentialGroup()
                        .addComponent(FondoEntrada)
                        .addGap(51, 51, 51))))
        );
        PanelEntradaLayout.setVerticalGroup(
            PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEntradaLayout.createSequentialGroup()
                .addGroup(PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Iconoderecha1)
                    .addComponent(CuadroEntrada))
                .addGap(18, 18, 18)
                .addComponent(FondoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(BotonEntrada)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(PanelEntrada, "card2");
        PanelEntrada.getAccessibleContext().setAccessibleName("");

        PanelInicio.setBackground(new java.awt.Color(153, 255, 153));
        PanelInicio.setMaximumSize(new java.awt.Dimension(600, 400));
        PanelInicio.setMinimumSize(new java.awt.Dimension(600, 400));
        PanelInicio.setPreferredSize(new java.awt.Dimension(600, 400));

        TextoInicio.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        TextoInicio.setForeground(new java.awt.Color(51, 51, 255));
        TextoInicio.setText("Rutas al aire libre");

        Salida.setText("Salir de la aplicacion");
        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });

        Rutas.setText("Ver Rutas");
        Rutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutasActionPerformed(evt);
            }
        });

        Usuario.setText("Registro");
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });

        Cuadro2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        Cuadro2.setForeground(new java.awt.Color(153, 0, 0));
        Cuadro2.setText("Email");

        Email.setToolTipText("");
        Email.setActionCommand("<Not Set>");
        Email.setName(""); // NOI18N

        Cuadro1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        Cuadro1.setForeground(new java.awt.Color(153, 0, 0));
        Cuadro1.setText("Contraseña");

        IniciarSesion.setText("Iniciar Sesión");
        IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelInicioLayout = new javax.swing.GroupLayout(PanelInicio);
        PanelInicio.setLayout(PanelInicioLayout);
        PanelInicioLayout.setHorizontalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextoInicio)
                .addGap(105, 105, 105)
                .addComponent(Logoderecha))
            .addGroup(PanelInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(Email))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelInicioLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(Cuadro2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cuadro1)
                .addGap(257, 257, 257))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInicioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IniciarSesion)
                    .addGroup(PanelInicioLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Rutas)
                        .addGap(105, 105, 105)
                        .addComponent(Salida)))
                .addGap(15, 15, 15))
        );
        PanelInicioLayout.setVerticalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInicioLayout.createSequentialGroup()
                .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logoderecha)
                    .addComponent(TextoInicio))
                .addGap(49, 49, 49)
                .addComponent(Cuadro2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Cuadro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(IniciarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salida)
                    .addComponent(Rutas)
                    .addComponent(Usuario))
                .addGap(33, 33, 33))
        );

        Email.getAccessibleContext().setAccessibleName("");

        getContentPane().add(PanelInicio, "card3");

        Seleccion.setBackground(new java.awt.Color(153, 255, 153));
        Seleccion.setMaximumSize(new java.awt.Dimension(600, 400));
        Seleccion.setMinimumSize(new java.awt.Dimension(600, 400));

        Cuadroinfo.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Cuadroinfo.setForeground(new java.awt.Color(0, 0, 255));
        Cuadroinfo.setText("Opciones ");

        BotonVolver.setText("Volver");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SeleccionLayout = new javax.swing.GroupLayout(Seleccion);
        Seleccion.setLayout(SeleccionLayout);
        SeleccionLayout.setHorizontalGroup(
            SeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeleccionLayout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(Cuadroinfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                .addComponent(Nombrecambia))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeleccionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonVolver)
                .addGap(24, 24, 24))
        );
        SeleccionLayout.setVerticalGroup(
            SeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeleccionLayout.createSequentialGroup()
                .addGroup(SeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SeleccionLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Nombrecambia))
                    .addGroup(SeleccionLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Cuadroinfo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(BotonVolver)
                .addGap(29, 29, 29))
        );

        getContentPane().add(Seleccion, "card4");

        CrearUsuarios.setBackground(new java.awt.Color(153, 255, 153));
        CrearUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        CrearUsuarios.setMaximumSize(new java.awt.Dimension(600, 400));
        CrearUsuarios.setMinimumSize(new java.awt.Dimension(600, 400));

        Texto.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Texto.setForeground(new java.awt.Color(0, 0, 255));
        Texto.setText("Crear Usuario");

        Nombre.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        Nombre.setText("Nuevo nombre:");

        apellido.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        apellido.setText("Nuevo apellido:");

        email.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        email.setText("Nuevo email:");

        contraseña.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        contraseña.setText("Nueva Contraseña:");

        rol.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        rol.setText("Elige tu rol:");

        eligerol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "diseñador", "profesor", "alumno" }));
        eligerol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eligerolActionPerformed(evt);
            }
        });

        VolverUsuarios.setText("Volver");
        VolverUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverUsuariosActionPerformed(evt);
            }
        });

        darbotonUsuario.setText("Crear Usuario");
        darbotonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darbotonUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CrearUsuariosLayout = new javax.swing.GroupLayout(CrearUsuarios);
        CrearUsuarios.setLayout(CrearUsuariosLayout);
        CrearUsuariosLayout.setHorizontalGroup(
            CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearUsuariosLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearUsuariosLayout.createSequentialGroup()
                        .addComponent(email)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearUsuariosLayout.createSequentialGroup()
                        .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre)
                            .addGroup(CrearUsuariosLayout.createSequentialGroup()
                                .addComponent(intronombre, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                .addGap(164, 164, 164)))
                        .addGap(84, 84, 84)
                        .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(introcontraseña))
                        .addGap(65, 65, 65))
                    .addGroup(CrearUsuariosLayout.createSequentialGroup()
                        .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(introemail)
                            .addComponent(introapellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearUsuariosLayout.createSequentialGroup()
                                .addComponent(rol)
                                .addGap(105, 105, 105))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearUsuariosLayout.createSequentialGroup()
                                .addComponent(eligerol, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(CrearUsuariosLayout.createSequentialGroup()
                                .addComponent(darbotonUsuario)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearUsuariosLayout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearUsuariosLayout.createSequentialGroup()
                        .addComponent(Texto)
                        .addGap(214, 214, 214)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearUsuariosLayout.createSequentialGroup()
                        .addComponent(VolverUsuarios)
                        .addContainerGap())))
        );
        CrearUsuariosLayout.setVerticalGroup(
            CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearUsuariosLayout.createSequentialGroup()
                .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearUsuariosLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(CrearUsuariosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Texto)
                        .addGap(42, 42, 42)
                        .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre)
                            .addComponent(contraseña))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(intronombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(introcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellido)
                    .addComponent(rol))
                .addGap(26, 26, 26)
                .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(introapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eligerol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(email)
                .addGap(18, 18, 18)
                .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(introemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(darbotonUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(VolverUsuarios)
                .addGap(15, 15, 15))
        );

        getContentPane().add(CrearUsuarios, "card5");

        RutasValidas.setBackground(new java.awt.Color(153, 255, 153));
        RutasValidas.setForeground(new java.awt.Color(255, 255, 255));
        RutasValidas.setMaximumSize(new java.awt.Dimension(600, 400));
        RutasValidas.setMinimumSize(new java.awt.Dimension(600, 400));

        VolverInicio.setText("Volver");
        VolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverInicioActionPerformed(evt);
            }
        });

        NombreRutas.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        NombreRutas.setForeground(new java.awt.Color(0, 0, 255));
        NombreRutas.setText("Rutas Validas");

        TableRutasValidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableRutasValidas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TableRutasValidasAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TableRutasValidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableRutasValidasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableRutasValidas);

        javax.swing.GroupLayout RutasValidasLayout = new javax.swing.GroupLayout(RutasValidas);
        RutasValidas.setLayout(RutasValidasLayout);
        RutasValidasLayout.setHorizontalGroup(
            RutasValidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RutasValidasLayout.createSequentialGroup()
                .addGroup(RutasValidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RutasValidasLayout.createSequentialGroup()
                        .addGroup(RutasValidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RutasValidasLayout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(NombreRutas))
                            .addGroup(RutasValidasLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RutasValidasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(VolverInicio)))
                .addContainerGap())
        );
        RutasValidasLayout.setVerticalGroup(
            RutasValidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RutasValidasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(NombreRutas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(VolverInicio)
                .addContainerGap())
        );

        VolverInicio.getAccessibleContext().setAccessibleName("Volver");

        getContentPane().add(RutasValidas, "card6");

        PuntosdeRuta.setBackground(new java.awt.Color(153, 255, 153));
        PuntosdeRuta.setMaximumSize(new java.awt.Dimension(600, 400));
        PuntosdeRuta.setMinimumSize(new java.awt.Dimension(600, 400));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("PuntosInteres");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setText("Puntos peligro");

        TablePuntosInteres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablePuntosInteres.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TablePuntosInteresAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(TablePuntosInteres);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TablePuntosPeligro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablePuntosPeligro.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TablePuntosPeligroAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(TablePuntosPeligro);

        javax.swing.GroupLayout PuntosdeRutaLayout = new javax.swing.GroupLayout(PuntosdeRuta);
        PuntosdeRuta.setLayout(PuntosdeRutaLayout);
        PuntosdeRutaLayout.setHorizontalGroup(
            PuntosdeRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PuntosdeRutaLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PuntosdeRutaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PuntosdeRutaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );
        PuntosdeRutaLayout.setVerticalGroup(
            PuntosdeRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PuntosdeRutaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PuntosdeRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(PuntosdeRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );

        getContentPane().add(PuntosdeRuta, "card7");

        ValoracionesdeRuta.setBackground(new java.awt.Color(153, 255, 153));
        ValoracionesdeRuta.setMaximumSize(new java.awt.Dimension(600, 400));
        ValoracionesdeRuta.setMinimumSize(new java.awt.Dimension(600, 400));

        jLabel4.setBackground(new java.awt.Color(102, 102, 255));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Valoraciones");

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TablaValoraciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaValoraciones.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TablaValoracionesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane5.setViewportView(TablaValoraciones);

        javax.swing.GroupLayout ValoracionesdeRutaLayout = new javax.swing.GroupLayout(ValoracionesdeRuta);
        ValoracionesdeRuta.setLayout(ValoracionesdeRutaLayout);
        ValoracionesdeRutaLayout.setHorizontalGroup(
            ValoracionesdeRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ValoracionesdeRutaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(ValoracionesdeRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ValoracionesdeRutaLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(227, 227, 227))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ValoracionesdeRutaLayout.createSequentialGroup()
                        .addGroup(ValoracionesdeRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18))))
        );
        ValoracionesdeRutaLayout.setVerticalGroup(
            ValoracionesdeRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ValoracionesdeRutaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addContainerGap())
        );

        getContentPane().add(ValoracionesdeRuta, "card8");

        Actividades.setBackground(new java.awt.Color(153, 255, 153));
        Actividades.setMaximumSize(new java.awt.Dimension(600, 400));
        Actividades.setMinimumSize(new java.awt.Dimension(600, 400));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 255));
        jLabel5.setText("Actividades");

        TablaActividades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaActividades.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TablaActividadesAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane6.setViewportView(TablaActividades);

        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ActividadesLayout = new javax.swing.GroupLayout(Actividades);
        Actividades.setLayout(ActividadesLayout);
        ActividadesLayout.setHorizontalGroup(
            ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActividadesLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActividadesLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(238, 238, 238))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActividadesLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ActividadesLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(20, 20, 20))))
        );
        ActividadesLayout.setVerticalGroup(
            ActividadesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ActividadesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(Actividades, "card9");

        DetallesRuta.setBackground(new java.awt.Color(153, 255, 153));
        DetallesRuta.setMaximumSize(new java.awt.Dimension(600, 400));
        DetallesRuta.setMinimumSize(new java.awt.Dimension(600, 400));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("Detalles");

        TablaDetallesruta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaDetallesruta.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TablaDetallesrutaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane7.setViewportView(TablaDetallesruta);

        jButton4.setText("Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DetallesRutaLayout = new javax.swing.GroupLayout(DetallesRuta);
        DetallesRuta.setLayout(DetallesRutaLayout);
        DetallesRutaLayout.setHorizontalGroup(
            DetallesRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetallesRutaLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(DetallesRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetallesRutaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(255, 255, 255))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetallesRutaLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DetallesRutaLayout.createSequentialGroup()
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        DetallesRutaLayout.setVerticalGroup(
            DetallesRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DetallesRutaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(23, 23, 23))
        );

        getContentPane().add(DetallesRuta, "card10");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEntradaActionPerformed
        PanelEntrada.setVisible(false);
        PanelInicio.setVisible(true);
    }//GEN-LAST:event_BotonEntradaActionPerformed

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea salir de la aplicacion", "Salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_SalidaActionPerformed

    private void RutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutasActionPerformed
        PanelInicio.setVisible(false);
        RutasValidas.setVisible(true);
        TableRutasValidas.setVisible(true);
        VolverInicio.setVisible(true);
        jScrollPane1.setVisible(true);
    }//GEN-LAST:event_RutasActionPerformed

    private void IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionActionPerformed
        String email = Email.getText();
        char[] passwordChars = Contraseña.getPassword();
        String password = new String(passwordChars);
        if (Teclado.validaemail(email) && Teclado.validapassword(password)) {
            DAOUsuario d = new DAOUsuario();
            Usuario U1 = d.encontrarUsuario(email, password);
            if (U1 != null) {
                PanelInicio.setVisible(false);
                Seleccion.setVisible(true);
                usuario = U1;
            }
            if (U1 == null) {
                JOptionPane.showMessageDialog(null, "No se encontro a ningun usuario con ese email o contraseña", "Volver", JOptionPane.PLAIN_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Formato mal introducido el email o contraseña", "Volver", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_IniciarSesionActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        CrearUsuarios.setVisible(true);
        PanelInicio.setVisible(false);
    }//GEN-LAST:event_UsuarioActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea volver a menu de inicio", "Volver", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == 0) {
            PanelInicio.setVisible(true);
            Seleccion.setVisible(false);
            Usuario = null;
        }

    }//GEN-LAST:event_BotonVolverActionPerformed

    private void eligerolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eligerolActionPerformed

    }//GEN-LAST:event_eligerolActionPerformed

    private void VolverUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverUsuariosActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea volver a menu de inicio", "Volver", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == 0) {
            CrearUsuarios.setVisible(false);
            PanelInicio.setVisible(true);
        }
    }//GEN-LAST:event_VolverUsuariosActionPerformed

    private void darbotonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darbotonUsuarioActionPerformed
        char[] passwordChars = introcontraseña.getPassword();
        String password = new String(passwordChars);
        String nombre = intronombre.getText();
        String apellidos = introapellido.getText();
        String emails = introemail.getText();
        Roles rol = null;
        String seleccion = eligerol.getSelectedItem().toString();
        if (seleccion.equals("administrador")) {
            rol = Roles.administrador;
        } else if (seleccion.equals("diseñador")) {
            rol = Roles.diseñador;
        } else if (seleccion.equals("profesor")) {
            rol = Roles.profesor;
        } else if (seleccion.equals("alumno")) {
            rol = Roles.alumno;
        }
        if (Teclado.validanombre(nombre) && Teclado.validaapellido(apellidos) && Teclado.validaemail(emails)) {
            Usuario usu = new Usuario(nombre, apellidos, emails, password, rol);
            DAOUsuario u1 = new DAOUsuario();
            if (u1.insertar(usu)) {
                JOptionPane.showMessageDialog(null, "Se creo el usuario correctamnete", "Bien", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "No se guardo el usuario en la base de datos, email ya existe", "Error", JOptionPane.PLAIN_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Formato mal introducido el formato de uno de los datos", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_darbotonUsuarioActionPerformed

    private void VolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverInicioActionPerformed
        CrearUsuarios.setVisible(false);
        PanelInicio.setVisible(true);
        TableRutasValidas.setVisible(false);
        VolverInicio.setVisible(false);
        jScrollPane1.setVisible(false);
    }//GEN-LAST:event_VolverInicioActionPerformed
    // Metodo para modificar la tabla de Rutas aprobadas
    private void TableRutasValidasAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TableRutasValidasAncestorAdded
        DAORutas daoruta = new DAORutas();
        List<Rutas> lisruta = daoruta.listaraprobadas();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Ruta");
        model.addColumn("Nombre");
        model.addColumn("Duracion");
        model.addColumn("Distancia");
        model.addColumn("Nombre del inicio de ruta");
        model.addColumn("Latitud ");
        model.addColumn("Longitud ");
        model.addColumn("Nombre del final de ruta");
        model.addColumn("Latitud");
        model.addColumn("Longitud");
        for (Rutas r : lisruta) {
            Object[] fila = {r.getIdRuta(), r.getNombre(), r.getDuracion(), r.getDistancia(), r.getNombre_inicioruta(), r.getLatitudInicial(), r.getLongitudInicial(), r.getNombre_finalruta(), r.getLatitudFinal(), r.getLongitudFinal()};
            model.addRow(fila);
        }
        TableRutasValidas.setModel(model);
        tamañocolumnasRutaValidas();
    }//GEN-LAST:event_TableRutasValidasAncestorAdded
    //Al hacer click en una fila de la tabla RutasValidas
    private void TableRutasValidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableRutasValidasMouseClicked
        int fila = TableRutasValidas.getSelectedRow(); // Fila que has clicado 
        if (fila != -1) {
            Object valorColumna0 = TableRutasValidas.getValueAt(fila, 0); // pillo la columna 0 
            // String resultado = valorColumna0.toString(); si hay que convertirla a toString 
            int resultado = (int) valorColumna0;// valor recogido
            //Para elegir entre diferentes opciones
            Object opcion = JOptionPane.showInputDialog(null, "Seleccione una opcion",
                    "Opcion de ruta", JOptionPane.QUESTION_MESSAGE, null,
                    new Object[]{"Seleccione", "Puntos Interes y Puntos Peligro","Detalles de la ruta", "Valoraciones", "Actividades"}, "Seleccione");
            switch (opcion.toString()) {
                case "Puntos Interes y Puntos Peligro" -> {
                    idrutaapipp = resultado;
                    RutasValidas.setVisible(false);
                    PuntosdeRuta.setVisible(true);
                }
                case "Valoraciones" -> {
                    idrutaapipp = resultado;
                    RutasValidas.setVisible(false);
                    ValoracionesdeRuta.setVisible(true);
                }
                case "Actividades" -> {
                    idrutaapipp = resultado;
                    RutasValidas.setVisible(false);
                    Actividades.setVisible(true);
                }
                case "Detalles de la ruta"->{
                    idrutaapipp = resultado;
                    RutasValidas.setVisible(false);
                    DetallesRuta.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_TableRutasValidasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea volver a  ver las rutas", "Volver", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == 0) {
            idrutaapipp = 1;
            RutasValidas.setVisible(true);
            PuntosdeRuta.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    // Metodo para modificar la tabla puntos interes
    private void TablePuntosInteresAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TablePuntosInteresAncestorAdded
        DAOPuntosinteres daopi = new DAOPuntosinteres();
        List<PuntosInteres> lispi = daopi.listar(idrutaapipp);// cambiar el metodo listar de dao puntos interes de Ruta ruta a int id 
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID PuntosInteres");
        model.addColumn("Nombre");
        model.addColumn("Latitud");
        model.addColumn("Longitud");
        model.addColumn("Elevacion");
        model.addColumn("Descripcion");
        for (PuntosInteres pp : lispi) {
            Object[] fila = {pp.getIdPuntosInteres(), pp.getNombre(), pp.getLatitud(), pp.getLongitud(), pp.getElevacion(), pp.getDescripcion()};
            model.addRow(fila);
        }
        TablePuntosInteres.setModel(model);

    }//GEN-LAST:event_TablePuntosInteresAncestorAdded
  // modica la tabla puntos peligro
    private void TablePuntosPeligroAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TablePuntosPeligroAncestorAdded
        DAOPuntospeligro daopp = new DAOPuntospeligro();
        List<PuntosPeligro> lispp = daopp.listar(idrutaapipp);// cambiar el metodo listar de dao puntos peligro de Ruta ruta a int id 
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID PuntosPeligro");
        model.addColumn("Nombre");
        model.addColumn("Latitud");
        model.addColumn("Longitud");
        model.addColumn("Elevacion");
        model.addColumn("Descripcion");
        for (PuntosPeligro pp : lispp) {
            Object[] fila = {pp.getIdPuntospeligro(), pp.getNombre(), pp.getLatitud(), pp.getLongitud(), pp.getElevacion(), pp.getDescripcion()};
            model.addRow(fila);
        }
        TablePuntosPeligro.setModel(model);
    }//GEN-LAST:event_TablePuntosPeligroAncestorAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea volver a ver las rutas", "Volver", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == 0) {
            idrutaapipp = 1;
            RutasValidas.setVisible(true);
            ValoracionesdeRuta.setVisible(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea volver a ver las rutas", "Volver", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == 0) {
            idrutaapipp = 1;
            RutasValidas.setVisible(true);
            Actividades.setVisible(false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
// modifica la tabla actividades
    private void TablaActividadesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TablaActividadesAncestorAdded
        DAOActividad daoa = new DAOActividad();
        List<Actividad> lisa = daoa.listar(idrutaapipp);// cambiar el metodo listar de dao valoraciones de Ruta ruta a int id 
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Actividad");
        model.addColumn("Nombre");
        for (Actividad a : lisa) {
            Object[] fila = {a.getIdActividad(),a.getNombre()};
            model.addRow(fila);
        }
        TablaActividades.setModel(model);
    }//GEN-LAST:event_TablaActividadesAncestorAdded

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         int respuesta = JOptionPane.showConfirmDialog(null, "Desea volver a ver las rutas", "Volver", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == 0) {
            idrutaapipp = 1;
            RutasValidas.setVisible(true);
            DetallesRuta.setVisible(false);
        }
    }//GEN-LAST:event_jButton4ActionPerformed
// Tabla valoraciones
    private void TablaDetallesrutaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TablaDetallesrutaAncestorAdded
         DAORutas daor = new DAORutas();
        Rutas ruta = daor.detallesextra(idrutaapipp);// cambiar el metodo listar de dao valoraciones de Ruta ruta a int id
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Ruta");
        model.addColumn("Clasificacion");
        model.addColumn("Nivel Esfuerzo");
        model.addColumn("Nivel Riesgo");
        model.addColumn("Estado Ruta");
        model.addColumn("Tipo Terreno");
        model.addColumn("Indicaciones");
        model.addColumn("Ruta Familiar");
        model.addColumn("Media Estrellas");
            Object[] fila = {ruta.getIdRuta(),ruta.getClasificacion(),ruta.getNivelEsfuerzo(),ruta.getNivelriesgo(),ruta.getEstadoRuta(),ruta.getTipoterreno(),ruta.getIndicaciones(),ruta.isRutaFamiliar(),ruta.getMediaEstrellas()};
            model.addRow(fila);
        TablaValoraciones.setModel(model);
    }//GEN-LAST:event_TablaDetallesrutaAncestorAdded

    // Tabla rellena con las valoraciones de un usuario
    private void TablaValoracionesAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TablaValoracionesAncestorAdded
        DAOValora daov = new DAOValora();
        List<Valora> lisv = daov.listar(idrutaapipp);// cambiar el metodo listar de dao valoraciones de Ruta ruta a int id
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Valora");
        model.addColumn("Dificultad");
        model.addColumn("Fecha");
        model.addColumn("Estrellas");
        model.addColumn("Interes Cultural");
        model.addColumn("Belleza");
        for (Valora v : lisv) {
            Object[] fila = {v.getIdValora(), v.getDificultad(), v.getFecha(), v.getEstrellas(), v.getInteresCultural(), v.getBelleza()};
            model.addRow(fila);
        }
        TablaValoraciones.setModel(model);
    }//GEN-LAST:event_TablaValoracionesAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SwingPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Actividades;
    private javax.swing.JButton BotonEntrada;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JPanel CrearUsuarios;
    private javax.swing.JLabel Cuadro1;
    private javax.swing.JLabel Cuadro2;
    private javax.swing.JLabel CuadroEntrada;
    private javax.swing.JLabel Cuadroinfo;
    private javax.swing.JPanel DetallesRuta;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel FondoEntrada;
    private javax.swing.JLabel Iconoderecha1;
    private javax.swing.JButton IniciarSesion;
    private javax.swing.JLabel Logoderecha;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NombreRutas;
    private javax.swing.JLabel Nombrecambia;
    private javax.swing.JPanel PanelEntrada;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JPanel PuntosdeRuta;
    private javax.swing.JButton Rutas;
    private javax.swing.JPanel RutasValidas;
    private javax.swing.JButton Salida;
    private javax.swing.JPanel Seleccion;
    private javax.swing.JTable TablaActividades;
    private javax.swing.JTable TablaDetallesruta;
    private javax.swing.JTable TablaValoraciones;
    private javax.swing.JTable TablePuntosInteres;
    private javax.swing.JTable TablePuntosPeligro;
    private javax.swing.JTable TableRutasValidas;
    private javax.swing.JLabel Texto;
    private javax.swing.JLabel TextoInicio;
    private javax.swing.JButton Usuario;
    private javax.swing.JPanel ValoracionesdeRuta;
    private javax.swing.JButton VolverInicio;
    private javax.swing.JButton VolverUsuarios;
    private javax.swing.JLabel apellido;
    private javax.swing.JLabel contraseña;
    private javax.swing.JButton darbotonUsuario;
    private javax.swing.JComboBox<String> eligerol;
    private javax.swing.JLabel email;
    private javax.swing.JTextField introapellido;
    private javax.swing.JPasswordField introcontraseña;
    private javax.swing.JTextField introemail;
    private javax.swing.JTextField intronombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel rol;
    // End of variables declaration//GEN-END:variables
}
