/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.reto_equipo3.Swing;

import com.mycompany.reto_equipo3.Calendario;
import com.mycompany.reto_equipo3.DAOS.AccesoABaseDatos;
import com.mycompany.reto_equipo3.DAOS.DAOCalendario;
import com.mycompany.reto_equipo3.DAOS.DAOUsuario;
import com.mycompany.reto_equipo3.Enums.Roles;
import com.mycompany.reto_equipo3.Rutas;
import com.mycompany.reto_equipo3.Usuario;
import com.mycompany.reto_equipo3.Validaciones.Teclado;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Iterator;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author salsa
 */
public class SwingPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form SwingPrincipal
     */
    Usuario usuario = null;
    Rutas R1 = null;

    public SwingPrincipal() {
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.out.println("Cierre deshabilitado.");
            }
        });
    }

    public void cambiarTexto() {
        if (usuario.getRol() == Roles.administrador) {
            Nombrecambia.setText("Opciones de Administrador");
        } else if (usuario.getRol() == Roles.diseñador) {
            Nombrecambia.setText("Opciones de Diseñador");
        } else if (usuario.getRol() == Roles.alumno) {
            Nombrecambia.setText("Opciones de Alumno");
        } else if (usuario.getRol() == Roles.profesor) {
            Nombrecambia.setText("Opciones de Profesor");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        PanelEntrada = new javax.swing.JPanel();
        CuadroEntrada = new javax.swing.JLabel();
        Iconoderecha1 = new javax.swing.JLabel();
        BotonEntrada = new javax.swing.JButton();
        FondoEntrada = new javax.swing.JLabel();
        PanelInicio = new javax.swing.JPanel();
        TextoInicio = new javax.swing.JLabel();
        Salida = new javax.swing.JButton();
        Rutas = new javax.swing.JButton();
        Usuario = new javax.swing.JButton();
        Cuadro2 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        Cuadro1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Contraseña = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        Seleccion = new javax.swing.JPanel();
        Cuadroinfo = new javax.swing.JLabel();
        Nombrecambia = new javax.swing.JLabel();
        BotonVolver = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        PanelCalendario = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacalendario = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        crearCalendario = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        borrarCalendario = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaBorrar = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        PanelEntrada.setBackground(new java.awt.Color(153, 255, 153));
        PanelEntrada.setForeground(new java.awt.Color(255, 255, 255));
        PanelEntrada.setMaximumSize(new java.awt.Dimension(600, 400));
        PanelEntrada.setMinimumSize(new java.awt.Dimension(600, 400));
        PanelEntrada.setPreferredSize(new java.awt.Dimension(600, 400));

        CuadroEntrada.setBackground(new java.awt.Color(0, 0, 0));
        CuadroEntrada.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        CuadroEntrada.setForeground(new java.awt.Color(51, 51, 255));
        CuadroEntrada.setText("Aplicacion de Rutas");
        CuadroEntrada.setAlignmentX(200.0F);
        CuadroEntrada.setAlignmentY(200.0F);

        BotonEntrada.setBackground(new java.awt.Color(51, 255, 51));
        BotonEntrada.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        BotonEntrada.setForeground(new java.awt.Color(0, 102, 0));
        BotonEntrada.setText("Iniciar aplicacion");
        BotonEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEntradaLayout = new javax.swing.GroupLayout(PanelEntrada);
        PanelEntrada.setLayout(PanelEntradaLayout);
        PanelEntradaLayout.setHorizontalGroup(
            PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEntradaLayout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addGroup(PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEntradaLayout.createSequentialGroup()
                        .addComponent(CuadroEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(Iconoderecha1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEntradaLayout.createSequentialGroup()
                        .addComponent(BotonEntrada)
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEntradaLayout.createSequentialGroup()
                        .addComponent(FondoEntrada)
                        .addGap(51, 51, 51))))
        );
        PanelEntradaLayout.setVerticalGroup(
            PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEntradaLayout.createSequentialGroup()
                .addGroup(PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Iconoderecha1)
                    .addComponent(CuadroEntrada))
                .addGap(18, 18, 18)
                .addComponent(FondoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(BotonEntrada)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(PanelEntrada, "card2");
        PanelEntrada.getAccessibleContext().setAccessibleName("");

        PanelInicio.setBackground(new java.awt.Color(153, 255, 153));
        PanelInicio.setMaximumSize(new java.awt.Dimension(600, 400));
        PanelInicio.setMinimumSize(new java.awt.Dimension(600, 400));
        PanelInicio.setPreferredSize(new java.awt.Dimension(600, 400));

        TextoInicio.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        TextoInicio.setForeground(new java.awt.Color(51, 51, 255));
        TextoInicio.setText("Rutas al aire libre");

        Salida.setText("Salir de la aplicacion");
        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });

        Rutas.setText("Ver Rutas");
        Rutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutasActionPerformed(evt);
            }
        });

        Usuario.setText("Registro");
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });

        Cuadro2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        Cuadro2.setForeground(new java.awt.Color(153, 0, 0));
        Cuadro2.setText("Email");

        Cuadro1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        Cuadro1.setForeground(new java.awt.Color(153, 0, 0));
        Cuadro1.setText("Contraseña");

        jButton1.setText("Iniciar Sesión");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelInicioLayout = new javax.swing.GroupLayout(PanelInicio);
        PanelInicio.setLayout(PanelInicioLayout);
        PanelInicioLayout.setHorizontalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextoInicio)
                .addGap(105, 105, 105)
                .addComponent(jLabel2))
            .addGroup(PanelInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(Email))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelInicioLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(Cuadro2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cuadro1)
                .addGap(257, 257, 257))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInicioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(PanelInicioLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Rutas)
                        .addGap(105, 105, 105)
                        .addComponent(Salida)))
                .addGap(15, 15, 15))
        );
        PanelInicioLayout.setVerticalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInicioLayout.createSequentialGroup()
                .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(TextoInicio))
                .addGap(49, 49, 49)
                .addComponent(Cuadro2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Cuadro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salida)
                    .addComponent(Rutas)
                    .addComponent(Usuario))
                .addGap(33, 33, 33))
        );

        getContentPane().add(PanelInicio, "card3");

        Cuadroinfo.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Cuadroinfo.setForeground(new java.awt.Color(0, 0, 255));
        Cuadroinfo.setText("Opciones ");

        BotonVolver.setText("Volver");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });

        jButton3.setText("Calendario");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SeleccionLayout = new javax.swing.GroupLayout(Seleccion);
        Seleccion.setLayout(SeleccionLayout);
        SeleccionLayout.setHorizontalGroup(
            SeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeleccionLayout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addGroup(SeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeleccionLayout.createSequentialGroup()
                        .addComponent(Cuadroinfo)
                        .addGap(191, 191, 191)
                        .addComponent(Nombrecambia))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeleccionLayout.createSequentialGroup()
                        .addComponent(BotonVolver)
                        .addGap(24, 24, 24))))
            .addGroup(SeleccionLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SeleccionLayout.setVerticalGroup(
            SeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeleccionLayout.createSequentialGroup()
                .addGroup(SeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cuadroinfo)
                    .addComponent(Nombrecambia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(121, 121, 121)
                .addComponent(BotonVolver)
                .addGap(29, 29, 29))
        );

        getContentPane().add(Seleccion, "card4");

        jButton4.setText("volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Calendario");

        tablacalendario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablacalendario.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablacalendarioAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tablacalendario);

        jButton6.setText("Crear calendario");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setText("Borrar calendario");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCalendarioLayout = new javax.swing.GroupLayout(PanelCalendario);
        PanelCalendario.setLayout(PanelCalendarioLayout);
        PanelCalendarioLayout.setHorizontalGroup(
            PanelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCalendarioLayout.createSequentialGroup()
                .addGroup(PanelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCalendarioLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1))
                    .addGroup(PanelCalendarioLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelCalendarioLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton6)
                        .addGap(26, 26, 26)
                        .addComponent(jButton5)
                        .addGap(64, 64, 64)
                        .addComponent(jButton4)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        PanelCalendarioLayout.setVerticalGroup(
            PanelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCalendarioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(PanelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addGap(36, 36, 36))
        );

        getContentPane().add(PanelCalendario, "card5");

        jLabel3.setText("FECHA");

        jLabel4.setText("DETALLES");

        jLabel5.setText("ID RUTA");

        jLabel6.setText("ID USUARIO");

        javax.swing.GroupLayout crearCalendarioLayout = new javax.swing.GroupLayout(crearCalendario);
        crearCalendario.setLayout(crearCalendarioLayout);
        crearCalendarioLayout.setHorizontalGroup(
            crearCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearCalendarioLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(crearCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearCalendarioLayout.createSequentialGroup()
                        .addGroup(crearCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(crearCalendarioLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(213, 213, 213))))
        );
        crearCalendarioLayout.setVerticalGroup(
            crearCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearCalendarioLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(crearCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(84, 84, 84)
                .addComponent(jLabel4)
                .addGap(87, 87, 87)
                .addComponent(jLabel5)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        getContentPane().add(crearCalendario, "card6");

        tablaBorrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaBorrar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tablaBorrarAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tablaBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaBorrarMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaBorrar);

        jButton7.setText("Volver");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout borrarCalendarioLayout = new javax.swing.GroupLayout(borrarCalendario);
        borrarCalendario.setLayout(borrarCalendarioLayout);
        borrarCalendarioLayout.setHorizontalGroup(
            borrarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(borrarCalendarioLayout.createSequentialGroup()
                .addGroup(borrarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(borrarCalendarioLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(borrarCalendarioLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jButton7)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        borrarCalendarioLayout.setVerticalGroup(
            borrarCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, borrarCalendarioLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addGap(19, 19, 19))
        );

        getContentPane().add(borrarCalendario, "card7");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEntradaActionPerformed
        PanelEntrada.setVisible(false);
        PanelInicio.setVisible(true);
    }//GEN-LAST:event_BotonEntradaActionPerformed

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea salir de la aplicacion", "Salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_SalidaActionPerformed

    private void RutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RutasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String email = Email.getText();
        char[] passwordChars = Contraseña.getPassword();
        String password = new String(passwordChars);
        if (Teclado.validaemail(email) && Teclado.validapassword(password)) {
            DAOUsuario d = new DAOUsuario();
            List<Usuario> usuarios = (List<Usuario>) d.listar();
            boolean existe = false;
            Iterator<Usuario> IT = usuarios.iterator();
            while (IT.hasNext() && !existe) {
                Usuario U1 = IT.next();
                if (d.encontrarUsuario(email, password) != null) {
                    existe = true;
                    PanelInicio.setVisible(false);
                    Seleccion.setVisible(true);
                    usuario = U1;
                    cambiarTexto();
                }
            }
            if (!existe) {
                JOptionPane.showMessageDialog(null, "No se encontro a ningun usuario con ese email o contraseña", "Volver", JOptionPane.PLAIN_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Formato mal introducido el email o contraseña", "Volver", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea volver a menu de inicio", "Volver", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == 0) {
            PanelInicio.setVisible(true);
            Seleccion.setVisible(false);
        }

    }//GEN-LAST:event_BotonVolverActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PanelCalendario.setVisible(true);
        Seleccion.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Seleccion.setVisible(true);
        PanelCalendario.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tablacalendarioAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablacalendarioAncestorAdded
        DAOCalendario daocal = new DAOCalendario();
        List<Calendario> liscal = daocal.listar();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Calendario");
        model.addColumn("Fecha");
        model.addColumn("Detalles");
        for (Calendario c : liscal) {
            Object[] fila = {c.getIdCalendario(), c.getFecha(), c.getDetalles()};
            model.addRow(fila);
        }
        tablacalendario.setModel(model);
    }//GEN-LAST:event_tablacalendarioAncestorAdded

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        crearCalendario.setVisible(true);
        PanelCalendario.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tablaBorrarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tablaBorrarAncestorAdded
        DAOCalendario daocal = new DAOCalendario();
        List<Calendario> liscal = daocal.listar();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Calendario");
        model.addColumn("Fecha");
        model.addColumn("Detalles");
        for (Calendario c : liscal) {
            Object[] fila = {c.getIdCalendario(), c.getFecha(), c.getDetalles()};
            model.addRow(fila);
        }
        tablaBorrar.setModel(model);
    }//GEN-LAST:event_tablaBorrarAncestorAdded

    private void tablaBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBorrarMouseClicked
        int row = tablaBorrar.rowAtPoint(evt.getPoint());
        int column = 1;
        int valor = 0;
        if (row != 1) {
            Object value = tablaBorrar.getValueAt(row, column);
            valor = (int) value;
            Object opcion = JOptionPane.showInputDialog(null, "Selecciona una opción: ", "Calendario", JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Crear", "Modificar", "Borrar"}, "Seleccione");
            String caso = (String) opcion;
            switch (caso) {
                case "Crear" -> {
                    
                }
                case "Modificar" -> {
                    
                }
                case "Borrar" -> {
                    DAOCalendario daocal = new DAOCalendario();
                    daocal.eliminar(valor);
                }
            }
        }


    }//GEN-LAST:event_tablaBorrarMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        borrarCalendario.setVisible(true);
        PanelCalendario.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        PanelCalendario.setVisible(true);
        borrarCalendario.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwingPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwingPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwingPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwingPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SwingPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEntrada;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JLabel Cuadro1;
    private javax.swing.JLabel Cuadro2;
    private javax.swing.JLabel CuadroEntrada;
    private javax.swing.JLabel Cuadroinfo;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel FondoEntrada;
    private javax.swing.JLabel Iconoderecha1;
    private javax.swing.JLabel Nombrecambia;
    private javax.swing.JPanel PanelCalendario;
    private javax.swing.JPanel PanelEntrada;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JButton Rutas;
    private javax.swing.JButton Salida;
    private javax.swing.JPanel Seleccion;
    private javax.swing.JLabel TextoInicio;
    private javax.swing.JButton Usuario;
    private javax.swing.JPanel borrarCalendario;
    private javax.swing.JPanel crearCalendario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaBorrar;
    private javax.swing.JTable tablacalendario;
    // End of variables declaration//GEN-END:variables
}
