-- MySQL Script generated by MySQL Workbench
-- Wed Apr 30 19:40:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(25) NOT NULL,
  `dni` CHAR(9) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `rol` ENUM('administrador', 'profesor', 'disenador', 'alumno') NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `user_UNIQUE` (`dni` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rutas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rutas` (
  `idRuta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `latitudInicial` DOUBLE NOT NULL,
  `longitudInicial` DOUBLE NOT NULL,
  `latitudFinal` DOUBLE NOT NULL,
  `longitudFinal` DOUBLE NOT NULL,
  `distancia` DOUBLE NOT NULL,
  `duracion` TIME NOT NULL,
  `desnivel` INT NOT NULL,
  `altitudMax` DOUBLE NOT NULL,
  `altitudMin` DOUBLE NOT NULL,
  `clasificacion` ENUM('circular', 'lineal') NOT NULL,
  `nivelEsfuerzo` TINYINT NOT NULL,
  `nivelRiesgo` TINYINT NOT NULL,
  `estadoRuta` TINYINT NOT NULL DEFAULT 0,
  `tipoTerreno` TINYINT NOT NULL,
  `indicaciones` TINYINT NOT NULL,
  `tipoActividad` ENUM('senderismo', 'bicicleta', 'raquetasNieve', 'otro') NOT NULL,
  `temporada` SET('primavera', 'verano', 'otono', 'invierno') NOT NULL,
  `accesibilidad` TINYINT NOT NULL,
  `rutaFamiliar` TINYINT NOT NULL,
  `archivoGPX` TEXT NULL,
  `recomendaciones` TEXT NULL,
  `zonaGeografica` VARCHAR(45) NOT NULL,
  `mediaEstrellas` DOUBLE NOT NULL DEFAULT 0,
  `usuCreador_id` INT NOT NULL,
  PRIMARY KEY (`idRuta`),
  INDEX `fk_rutas_usuarios_idx` (`usuCreador_id` ASC) VISIBLE,
  CONSTRAINT `fk_rutas_usuarios`
    FOREIGN KEY (`usuCreador_id`)
    REFERENCES `mydb`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`valora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`valora` (
  `dificultad` TINYINT NOT NULL,
  `belleza` TINYINT NOT NULL,
  `interesCultural` TINYINT NOT NULL,
  `fecha` DATE NOT NULL,
  `valoracionTecnica` TEXT NULL,
  `resena` TEXT NULL,
  `usuarios_id` INT NOT NULL,
  `rutas_id` INT NOT NULL,
  `estrellas` TINYINT NOT NULL,
  PRIMARY KEY (`usuarios_id`, `rutas_id`),
  INDEX `fk_valora_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_valora_rutas1_idx` (`rutas_id` ASC) VISIBLE,
  CONSTRAINT `fk_valora_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_valora_rutas1`
    FOREIGN KEY (`rutas_id`)
    REFERENCES `mydb`.`rutas` (`idRuta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trackpoints`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trackpoints` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `latitud` DOUBLE NOT NULL,
  `longitud` DOUBLE NOT NULL,
  `elevacion` DOUBLE NOT NULL,
  `timeStamp` DATETIME NOT NULL,
  `rutas_idRuta` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_trackpoints_rutas1_idx` (`rutas_idRuta` ASC) VISIBLE,
  CONSTRAINT `fk_trackpoints_rutas1`
    FOREIGN KEY (`rutas_idRuta`)
    REFERENCES `mydb`.`rutas` (`idRuta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`waypoints`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`waypoints` (
  `descripcion` TEXT NULL,
  `imagenes` TEXT NULL,
  `trackpoints_id` INT NOT NULL,
  PRIMARY KEY (`trackpoints_id`),
  CONSTRAINT `fk_waypoints_trackpoints1`
    FOREIGN KEY (`trackpoints_id`)
    REFERENCES `mydb`.`trackpoints` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wInteres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`wInteres` (
  `nombre` VARCHAR(40) NOT NULL,
  `tipo` ENUM('historico_arqueologico', 'naturaleza', 'mirador', 'area de descanso', 'punto de agua', 'refugio', 'cultural', 'geologico', 'fauna', 'botanico') NOT NULL,
  `caracteristicas` TEXT NULL,
  `id_waypoint` INT NOT NULL,
  PRIMARY KEY (`id_waypoint`),
  INDEX `fk_puntos_interes_waypoints1_idx` (`id_waypoint` ASC) VISIBLE,
  CONSTRAINT `fk_puntos_interes_waypoints1`
    FOREIGN KEY (`id_waypoint`)
    REFERENCES `mydb`.`waypoints` (`trackpoints_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wPeligro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`wPeligro` (
  `kilometro` DOUBLE NOT NULL,
  `gravedad` TINYINT NOT NULL,
  `id_waypoint` INT NOT NULL,
  PRIMARY KEY (`id_waypoint`),
  INDEX `fk_puntos_peligro_waypoints1_idx` (`id_waypoint` ASC) VISIBLE,
  CONSTRAINT `fk_puntos_peligro_waypoints1`
    FOREIGN KEY (`id_waypoint`)
    REFERENCES `mydb`.`waypoints` (`trackpoints_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`calendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`calendario` (
  `idCalendario` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `detalles` VARCHAR(45) NOT NULL,
  `recomendaciones` VARCHAR(45) NOT NULL,
  `usuarios_id` INT NOT NULL,
  `rutas_id` INT NOT NULL,
  PRIMARY KEY (`idCalendario`),
  INDEX `fk_calendario_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_calendario_rutas1_idx` (`rutas_id` ASC) VISIBLE,
  CONSTRAINT `fk_calendario_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calendario_rutas1`
    FOREIGN KEY (`rutas_id`)
    REFERENCES `mydb`.`rutas` (`idRuta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
