-- MySQL Script generated by MySQL Workbench
-- Tue Apr 29 23:43:16 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema retoDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema retoDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `retoDB` DEFAULT CHARACTER SET utf8 ;
USE `retoDB` ;

-- -----------------------------------------------------
-- Table `retoDB`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retoDB`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `rol` ENUM('administrador', 'profesor', 'disenador', 'alumno') NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `user_UNIQUE` (`user` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retoDB`.`rutas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retoDB`.`rutas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `puntoInicial` VARCHAR(45) NOT NULL,
  `puntoFinal` VARCHAR(45) NOT NULL,
  `distancia` INT NOT NULL,
  `duracion` TIME NOT NULL,
  `desnivel` INT NOT NULL,
  `altitudMax` INT NOT NULL,
  `altitudMin` INT NOT NULL,
  `clasificacion` VARCHAR(45) NOT NULL,
  `nivelEsfuerzo` TINYINT NOT NULL,
  `nivelRiesgo` TINYINT NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rutas_usuarios_idx` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_rutas_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `retoDB`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retoDB`.`valora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retoDB`.`valora` (
  `dificultad` VARCHAR(45) NOT NULL,
  `belleza` TINYINT NOT NULL,
  `interesCultural` TINYINT NOT NULL,
  `fecha` DATE NOT NULL,
  `valoracionTecnica` VARCHAR(45) NULL,
  `resena` VARCHAR(45) NULL,
  `usuarios_id` INT NOT NULL,
  `rutas_id` INT NOT NULL,
  PRIMARY KEY (`usuarios_id`, `rutas_id`),
  INDEX `fk_valora_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_valora_rutas1_idx` (`rutas_id` ASC) VISIBLE,
  CONSTRAINT `fk_valora_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `retoDB`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_valora_rutas1`
    FOREIGN KEY (`rutas_id`)
    REFERENCES `retoDB`.`rutas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retoDB`.`puntos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retoDB`.`puntos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `imagenes` FLOAT NOT NULL,
  `latitud` FLOAT NOT NULL,
  `longitud` VARCHAR(45) NOT NULL,
  `rutas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_puntos_rutas1_idx` (`rutas_id` ASC) VISIBLE,
  CONSTRAINT `fk_puntos_rutas1`
    FOREIGN KEY (`rutas_id`)
    REFERENCES `retoDB`.`rutas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retoDB`.`puntos_interes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retoDB`.`puntos_interes` (
  `nombre` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `caracteristicas` VARCHAR(45) NOT NULL,
  `puntos_id` INT NOT NULL,
  PRIMARY KEY (`puntos_id`),
  CONSTRAINT `fk_puntos_interes_puntos1`
    FOREIGN KEY (`puntos_id`)
    REFERENCES `retoDB`.`puntos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retoDB`.`puntos_peligro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retoDB`.`puntos_peligro` (
  `kilometro` INT NOT NULL,
  `gravedad` VARCHAR(45) NOT NULL,
  `puntos_id` INT NOT NULL,
  PRIMARY KEY (`puntos_id`),
  CONSTRAINT `fk_puntos_peligro_puntos1`
    FOREIGN KEY (`puntos_id`)
    REFERENCES `retoDB`.`puntos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retoDB`.`calendario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `retoDB`.`calendario` (
  `fecha` DATE NOT NULL,
  `detalles` VARCHAR(45) NOT NULL,
  `recomendaciones` VARCHAR(45) NOT NULL,
  `usuarios_id` INT NOT NULL,
  `rutas_id` INT NOT NULL,
  PRIMARY KEY (`fecha`, `usuarios_id`),
  INDEX `fk_calendario_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_calendario_rutas1_idx` (`rutas_id` ASC) VISIBLE,
  CONSTRAINT `fk_calendario_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `retoDB`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calendario_rutas1`
    FOREIGN KEY (`rutas_id`)
    REFERENCES `retoDB`.`rutas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
