/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.reto_equipo3.Swing;

import com.mycompany.reto_equipo3.DAOS.DAOUsuario;
import com.mycompany.reto_equipo3.Enums.Roles;
import com.mycompany.reto_equipo3.Rutas;
import com.mycompany.reto_equipo3.Usuario;
import com.mycompany.reto_equipo3.Validaciones.Teclado;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author salsa
 */
public class SwingPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form SwingPrincipal
     */
    Usuario usuario = null;
    Rutas R1 = null;

    public SwingPrincipal() {
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.out.println("Cierre deshabilitado.");
            }
        });
    }

    public void cambiarTexto() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        PanelEntrada = new javax.swing.JPanel();
        CuadroEntrada = new javax.swing.JLabel();
        Iconoderecha1 = new javax.swing.JLabel();
        BotonEntrada = new javax.swing.JButton();
        FondoEntrada = new javax.swing.JLabel();
        PanelInicio = new javax.swing.JPanel();
        TextoInicio = new javax.swing.JLabel();
        Salida = new javax.swing.JButton();
        Rutas = new javax.swing.JButton();
        Usuario = new javax.swing.JButton();
        Cuadro2 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        Cuadro1 = new javax.swing.JLabel();
        IniciarSesion = new javax.swing.JButton();
        Contraseña = new javax.swing.JPasswordField();
        Logoderecha = new javax.swing.JLabel();
        Seleccion = new javax.swing.JPanel();
        Cuadroinfo = new javax.swing.JLabel();
        Nombrecambia = new javax.swing.JLabel();
        BotonVolver = new javax.swing.JButton();
        CrearUsuarios = new javax.swing.JPanel();
        Texto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        intronombre = new javax.swing.JTextField();
        apellido = new javax.swing.JLabel();
        introapellido = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        introemail = new javax.swing.JTextField();
        contraseña = new javax.swing.JLabel();
        rol = new javax.swing.JLabel();
        eligerol = new javax.swing.JComboBox<>();
        introcontraseña = new javax.swing.JPasswordField();
        VolverUsuarios = new javax.swing.JButton();
        darbotonUsuario = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        PanelEntrada.setBackground(new java.awt.Color(153, 255, 153));
        PanelEntrada.setForeground(new java.awt.Color(255, 255, 255));
        PanelEntrada.setMaximumSize(new java.awt.Dimension(600, 400));
        PanelEntrada.setMinimumSize(new java.awt.Dimension(600, 400));
        PanelEntrada.setPreferredSize(new java.awt.Dimension(600, 400));

        CuadroEntrada.setBackground(new java.awt.Color(0, 0, 0));
        CuadroEntrada.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        CuadroEntrada.setForeground(new java.awt.Color(51, 51, 255));
        CuadroEntrada.setText("Aplicacion de Rutas");
        CuadroEntrada.setAlignmentX(200.0F);
        CuadroEntrada.setAlignmentY(200.0F);

        Iconoderecha1.setIcon(new javax.swing.ImageIcon("D:\\Usuarios\\Dam121\\Desktop\\Proyecto\\DAM1_EQUIPO3_2425\\Reto_equipo3\\src\\Imagenes\\Imagen-logo-equipo5050.png")); // NOI18N

        BotonEntrada.setBackground(new java.awt.Color(51, 255, 51));
        BotonEntrada.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        BotonEntrada.setForeground(new java.awt.Color(0, 102, 0));
        BotonEntrada.setText("Iniciar aplicacion");
        BotonEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEntradaActionPerformed(evt);
            }
        });

        FondoEntrada.setIcon(new javax.swing.ImageIcon("D:\\Usuarios\\Dam121\\Desktop\\Proyecto\\DAM1_EQUIPO3_2425\\Reto_equipo3\\src\\Imagenes\\ImagenfondoInicio.jpg")); // NOI18N

        javax.swing.GroupLayout PanelEntradaLayout = new javax.swing.GroupLayout(PanelEntrada);
        PanelEntrada.setLayout(PanelEntradaLayout);
        PanelEntradaLayout.setHorizontalGroup(
            PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEntradaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEntradaLayout.createSequentialGroup()
                        .addComponent(CuadroEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(Iconoderecha1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEntradaLayout.createSequentialGroup()
                        .addComponent(BotonEntrada)
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEntradaLayout.createSequentialGroup()
                        .addComponent(FondoEntrada)
                        .addGap(51, 51, 51))))
        );
        PanelEntradaLayout.setVerticalGroup(
            PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEntradaLayout.createSequentialGroup()
                .addGroup(PanelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Iconoderecha1)
                    .addComponent(CuadroEntrada))
                .addGap(18, 18, 18)
                .addComponent(FondoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(BotonEntrada)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(PanelEntrada, "card2");
        PanelEntrada.getAccessibleContext().setAccessibleName("");

        PanelInicio.setBackground(new java.awt.Color(153, 255, 153));
        PanelInicio.setMaximumSize(new java.awt.Dimension(600, 400));
        PanelInicio.setMinimumSize(new java.awt.Dimension(600, 400));
        PanelInicio.setPreferredSize(new java.awt.Dimension(600, 400));

        TextoInicio.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        TextoInicio.setForeground(new java.awt.Color(51, 51, 255));
        TextoInicio.setText("Rutas al aire libre");

        Salida.setText("Salir de la aplicacion");
        Salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalidaActionPerformed(evt);
            }
        });

        Rutas.setText("Ver Rutas");
        Rutas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RutasActionPerformed(evt);
            }
        });

        Usuario.setText("Registro");
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });

        Cuadro2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        Cuadro2.setForeground(new java.awt.Color(153, 0, 0));
        Cuadro2.setText("Email");

        Email.setToolTipText("");
        Email.setActionCommand("<Not Set>");
        Email.setName(""); // NOI18N

        Cuadro1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        Cuadro1.setForeground(new java.awt.Color(153, 0, 0));
        Cuadro1.setText("Contraseña");

        IniciarSesion.setText("Iniciar Sesión");
        IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesionActionPerformed(evt);
            }
        });

        Logoderecha.setIcon(new javax.swing.ImageIcon("D:\\Usuarios\\Dam121\\Desktop\\Proyecto\\DAM1_EQUIPO3_2425\\Reto_equipo3\\src\\Imagenes\\Imagen-logo-equipo5050.png")); // NOI18N

        javax.swing.GroupLayout PanelInicioLayout = new javax.swing.GroupLayout(PanelInicio);
        PanelInicio.setLayout(PanelInicioLayout);
        PanelInicioLayout.setHorizontalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextoInicio)
                .addGap(105, 105, 105)
                .addComponent(Logoderecha))
            .addGroup(PanelInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(Email))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelInicioLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(Cuadro2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Cuadro1)
                .addGap(257, 257, 257))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInicioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IniciarSesion)
                    .addGroup(PanelInicioLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Rutas)
                        .addGap(105, 105, 105)
                        .addComponent(Salida)))
                .addGap(15, 15, 15))
        );
        PanelInicioLayout.setVerticalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInicioLayout.createSequentialGroup()
                .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Logoderecha)
                    .addComponent(TextoInicio))
                .addGap(49, 49, 49)
                .addComponent(Cuadro2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Cuadro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(IniciarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salida)
                    .addComponent(Rutas)
                    .addComponent(Usuario))
                .addGap(33, 33, 33))
        );

        Email.getAccessibleContext().setAccessibleName("");

        getContentPane().add(PanelInicio, "card3");

        Cuadroinfo.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Cuadroinfo.setForeground(new java.awt.Color(0, 0, 255));
        Cuadroinfo.setText("Opciones ");

        Nombrecambia.setIcon(new javax.swing.ImageIcon("D:\\Usuarios\\Dam121\\Desktop\\Proyecto\\DAM1_EQUIPO3_2425\\Reto_equipo3\\src\\Imagenes\\Imagen-logo-equipo5050.png")); // NOI18N

        BotonVolver.setText("Volver");
        BotonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SeleccionLayout = new javax.swing.GroupLayout(Seleccion);
        Seleccion.setLayout(SeleccionLayout);
        SeleccionLayout.setHorizontalGroup(
            SeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeleccionLayout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addGroup(SeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeleccionLayout.createSequentialGroup()
                        .addComponent(Cuadroinfo)
                        .addGap(191, 191, 191)
                        .addComponent(Nombrecambia))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeleccionLayout.createSequentialGroup()
                        .addComponent(BotonVolver)
                        .addGap(24, 24, 24))))
        );
        SeleccionLayout.setVerticalGroup(
            SeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeleccionLayout.createSequentialGroup()
                .addGroup(SeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cuadroinfo)
                    .addComponent(Nombrecambia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 298, Short.MAX_VALUE)
                .addComponent(BotonVolver)
                .addGap(29, 29, 29))
        );

        getContentPane().add(Seleccion, "card4");

        CrearUsuarios.setBackground(new java.awt.Color(153, 255, 153));
        CrearUsuarios.setForeground(new java.awt.Color(255, 255, 255));

        Texto.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Texto.setForeground(new java.awt.Color(0, 0, 255));
        Texto.setText("Crear Usuario");

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Usuarios\\Dam121\\Desktop\\Proyecto\\DAM1_EQUIPO3_2425\\Reto_equipo3\\src\\Imagenes\\Imagen-logo-equipo5050.png")); // NOI18N

        Nombre.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        Nombre.setText("Nuevo nombre:");

        apellido.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        apellido.setText("Nuevo apellido:");

        email.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        email.setText("Nuevo email:");

        contraseña.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        contraseña.setText("Nueva Contraseña:");

        rol.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        rol.setText("Elige tu rol:");

        eligerol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "administrador", "diseñador", "profesor", "alumno" }));
        eligerol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eligerolActionPerformed(evt);
            }
        });

        VolverUsuarios.setText("Volver");
        VolverUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverUsuariosActionPerformed(evt);
            }
        });

        darbotonUsuario.setText("Crear Usuario");
        darbotonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darbotonUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CrearUsuariosLayout = new javax.swing.GroupLayout(CrearUsuarios);
        CrearUsuarios.setLayout(CrearUsuariosLayout);
        CrearUsuariosLayout.setHorizontalGroup(
            CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearUsuariosLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearUsuariosLayout.createSequentialGroup()
                        .addComponent(email)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearUsuariosLayout.createSequentialGroup()
                        .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre)
                            .addGroup(CrearUsuariosLayout.createSequentialGroup()
                                .addComponent(intronombre, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                .addGap(164, 164, 164)))
                        .addGap(84, 84, 84)
                        .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(contraseña, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(introcontraseña))
                        .addGap(65, 65, 65))
                    .addGroup(CrearUsuariosLayout.createSequentialGroup()
                        .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(introemail)
                            .addComponent(introapellido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearUsuariosLayout.createSequentialGroup()
                                .addComponent(rol)
                                .addGap(105, 105, 105))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearUsuariosLayout.createSequentialGroup()
                                .addComponent(eligerol, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(CrearUsuariosLayout.createSequentialGroup()
                                .addComponent(darbotonUsuario)
                                .addContainerGap())))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearUsuariosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearUsuariosLayout.createSequentialGroup()
                        .addComponent(Texto)
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearUsuariosLayout.createSequentialGroup()
                        .addComponent(VolverUsuarios)
                        .addContainerGap())))
        );
        CrearUsuariosLayout.setVerticalGroup(
            CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearUsuariosLayout.createSequentialGroup()
                .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Texto)
                        .addComponent(jLabel1))
                    .addGroup(CrearUsuariosLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nombre)
                            .addComponent(contraseña))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(intronombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(introcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellido)
                    .addComponent(rol))
                .addGap(26, 26, 26)
                .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(introapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eligerol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(email)
                .addGap(18, 18, 18)
                .addGroup(CrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(introemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(darbotonUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(VolverUsuarios)
                .addGap(15, 15, 15))
        );

        getContentPane().add(CrearUsuarios, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEntradaActionPerformed
        PanelEntrada.setVisible(false);
        PanelInicio.setVisible(true);
    }//GEN-LAST:event_BotonEntradaActionPerformed

    private void SalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalidaActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea salir de la aplicacion", "Salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_SalidaActionPerformed

    private void RutasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RutasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RutasActionPerformed

    private void IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionActionPerformed
        String email = Email.getText();
        char[] passwordChars = Contraseña.getPassword();
        String password = new String(passwordChars);
        if (Teclado.validaemail(email) && Teclado.validapassword(password)) {
            DAOUsuario d = new DAOUsuario();
            Usuario U1 = d.encontrarUsuario(email, password);
            if (U1 != null) {
                PanelInicio.setVisible(false);
                Seleccion.setVisible(true);
                usuario = U1;
                cambiarTexto();
            }
            if (U1 == null) {
                JOptionPane.showMessageDialog(null, "No se encontro a ningun usuario con ese email o contraseña", "Volver", JOptionPane.PLAIN_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Formato mal introducido el email o contraseña", "Volver", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_IniciarSesionActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        CrearUsuarios.setVisible(true);
        PanelInicio.setVisible(false);
    }//GEN-LAST:event_UsuarioActionPerformed

    private void BotonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVolverActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea volver a menu de inicio", "Volver", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == 0) {
            PanelInicio.setVisible(true);
            Seleccion.setVisible(false);
        }

    }//GEN-LAST:event_BotonVolverActionPerformed

    private void eligerolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eligerolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eligerolActionPerformed

    private void VolverUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverUsuariosActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea volver a menu de inicio", "Volver", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == 0) {
            CrearUsuarios.setVisible(false);
            PanelInicio.setVisible(true);
        }
    }//GEN-LAST:event_VolverUsuariosActionPerformed

    private void darbotonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darbotonUsuarioActionPerformed
        char[] passwordChars = introcontraseña.getPassword();
        String password = new String(passwordChars);
        String nombre = intronombre.getText();
        String apellidos = introapellido.getText();
        String emails = introemail.getText();
        Roles rol = null;
        String seleccion = eligerol.getSelectedItem().toString();
        if (seleccion.equals("administrador")) {
            rol = Roles.administrador;
        } else if (seleccion.equals("diseñador")) {
            rol = Roles.diseñador;
        } else if (seleccion.equals("profesor")) {
            rol = Roles.profesor;
        } else if (seleccion.equals("alumno")) {
            rol = Roles.alumno;
        }
        if (Teclado.validanombre(nombre) && Teclado.validaapellido(apellidos) && Teclado.validaemail(emails)) {
            Usuario usu = new Usuario(nombre, apellidos, emails, password, rol);
            DAOUsuario u1 = new DAOUsuario();
            if (u1.insertar(usu)) {
                JOptionPane.showMessageDialog(null, "Se creo el usuario correctamnete", "Bien", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "No se guardo el usuario en la base de datos, email ya existe", "Error", JOptionPane.PLAIN_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Formato mal introducido el formato de uno de los datos", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_darbotonUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SwingPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEntrada;
    private javax.swing.JButton BotonVolver;
    private javax.swing.JPasswordField Contraseña;
    private javax.swing.JPanel CrearUsuarios;
    private javax.swing.JLabel Cuadro1;
    private javax.swing.JLabel Cuadro2;
    private javax.swing.JLabel CuadroEntrada;
    private javax.swing.JLabel Cuadroinfo;
    private javax.swing.JTextField Email;
    private javax.swing.JLabel FondoEntrada;
    private javax.swing.JLabel Iconoderecha1;
    private javax.swing.JButton IniciarSesion;
    private javax.swing.JLabel Logoderecha;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nombrecambia;
    private javax.swing.JPanel PanelEntrada;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JButton Rutas;
    private javax.swing.JButton Salida;
    private javax.swing.JPanel Seleccion;
    private javax.swing.JLabel Texto;
    private javax.swing.JLabel TextoInicio;
    private javax.swing.JButton Usuario;
    private javax.swing.JButton VolverUsuarios;
    private javax.swing.JLabel apellido;
    private javax.swing.JLabel contraseña;
    private javax.swing.JButton darbotonUsuario;
    private javax.swing.JComboBox<String> eligerol;
    private javax.swing.JLabel email;
    private javax.swing.JTextField introapellido;
    private javax.swing.JPasswordField introcontraseña;
    private javax.swing.JTextField introemail;
    private javax.swing.JTextField intronombre;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel rol;
    // End of variables declaration//GEN-END:variables
}
